name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Build VSIX
      shell: bash
      run: |
        npm install
        npm install -g vsce
        vsce package

